quest-academia/qa-rails-ec-training-azalea

- README.md
　READMEファイルの修正
　https://github.com/quest-academia/qa-rails-ec-training-azalea/issues/4
　一度間違えて #1でbranchを切り、pushまでしてしまいました。その後、push、commit、addを取り消し、#1のbranchを削除した後、新しく#4のブランチを作り直しました。取り消したのは初めてだったため、正しく修正されてるか不安です。
> #4 プルリク説明動画視聴、READMEに氏名記入（さっしゅん）

- db/seeds.rb
seedにUser関連のデータを追加
https://github.com/quest-academia/qa-rails-ec-training-azalea/issues/16
・schemaで記載されているカラムの順番だとやり辛かったので、順番を変えてseedに書き込みました。
・前期では「漫画太郎」のようにUserがユニークだった気がします。今回は「山田」などと、一般的すぎて面白みに欠けるかなあと内心思ってます。。笑
以下コンソール画面のスクショです。
> #16 seedsにUser関連追加

- app/models/user.rb
Userモデルのバリデーションを作成
- https://github.com/quest-academia/qa-rails-ec-training-azalea/issues/15
`zipcode` の varidate `format: {with: /^\d{7}$/}` はよく分からないままコピペしています。
`format: { with: VALID_EMAIL_REGEX }`, `format: { with: VALID_PHONE_REGEX }` も、多分そういうものなんだろうな、ぐらいの認識です。
`user_classification` とはなんなのか、(ユーザー識別とは？)よく分からず、放置しています。出品者と購入者、とかでしょうか。だとしたら、バリデーションはどうなるのでしょう。よく分からないです。
- [  ✔︎ ] 動作確認は実行した?
- https://gist.github.com/shimadama/b8493fc357fc93bbb2b7e56a0074ba5a
> #15 Validation Users関連

- config/rubocop/rubocop.yml
config/rubocop/rubocop.ymlに文言をコピペ→警告文が消えるのを動作確認済
https://github.com/quest-academia/qa-rails-ec-training-azalea/issues/26
貼り付ける箇所に迷ったため、最下部にコメントとともに貼り付けました。
> #26 rubocop警告文の対処

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/products.scss
- app/views/layouts/_footer.html.erb
- app/views/layouts/_header.html.erb
- app/views/layouts/application.html.erb
- app/views/products/show.html.erb
- app/views/users/show.html.erb
・htmlの共通化
　・application.html.erb編集
　・show.html.erbの編集
　・_footer, _headerページの作成
・show画面のレイアウト編集
（レイアウトのズレを防ぐ目的でmargin-leftを20emに設定していましたが、今回の変更で逆に左に大きくずれたので35emに戻しました。）
https://github.com/quest-academia/qa-rails-ec-training-azalea/issues/27
```
<link
rel="stylesheet"
href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
...
```
のコードの有無に関わらずに動作しましたが、指定に基づき入れておきました。
(margin-left: 35em)
> #27 htmlファイルの共通化

- Gemfile
- Gemfile.lock
> binding.pry 関連のgemを追加

- app/assets/stylesheets/custom.scss
- app/assets/stylesheets/products.scss
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/layouts/_flash_messages.html.erb
- app/views/layouts/application.html.erb
- app/views/users/edit.html.erb
- ユーザ情報更新の実装
- 更新成功なら、user詳細画面へ、失敗なら、user修正画面へ飛ぶ
- 更新成功・失敗時にアラートを出す
- https://github.com/quest-academia/qa-rails-ec-training-azalea/issues/33
- アラート実装に関して、application.rb にflash を利用して設置したが、これで良かったのか。
- パスワード再入力機能の実装
- パスワードを未記入の際の、元のまま登録する機能の実装
- [ ✔︎ ] 動作確認は実行した?
- データが書き代わり、正常に表示されることを確認
- 更新成功なら、user詳細画面へ、失敗なら、user修正画面へ飛ぶことを確認
- アラートが正常に表示されることを確認
- [ ✔︎ ] rubocopは実行した?
- https://qiita.com/you8/items/21bcb08c9680200caea4
- 編集機能の実装
- https://getbootstrap.jp/docs/4.3/components/alerts/
- alert の見た目実装のbootstrap
> #33　ユーザー情報更新

- app/views/products/show.html.erb
- app/views/sessions/new.html.erb
> レイアウト崩れ修正のため、全体をmainで囲んだ

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/helpers/sessions_helper.rb
- app/views/layouts/_header.html.erb
- config/routes.rb
- https://github.com/quest-academia/qa-rails-ec-training-azalea/issues/36
動作確認も兼ねて、headerにユーザの名前を表示するようにしたのですが、今やるのは余計だったかも、と思っています。
なし
- https://railstutorial.jp/chapters/log_in_log_out?version=4.2#sec-logging_in
> #36 ログイン、ログアウト処理

- Gemfile
- Gemfile.lock
- app/controllers/users_controller.rb
- app/models/order.rb
- app/models/order_detail.rb
- app/models/shipment_status.rb
- config/application.rb
- config/locales/ja.yml
・エラー文を日本語にするgemの追加
・config/application.rb に追記
・ja.ymlに日本語ver.を明記
https://github.com/quest-academia/qa-rails-ec-training-azalea/issues/34
以下、実行結果です。
signup画面がまだ実装されてなかったので、コンソール上での結果のみです。
> #34  エラーメッセージの日本語化

- app/models/order.rb
- app/models/order_detail.rb
- db/seeds.rb
seedにOrder関連投入
- https://github.com/quest-academia/qa-rails-ec-training-azalea/issues/18
コードの綺麗な書き方
> #18 データ投入 Seed Orders関連

- app/controllers/static_pages_controller.rb
- app/helpers/sessions_helper.rb
- app/views/static_pages/home.html.erb
- config/routes.rb
- TOPページを作成
- static_pages_controllerを作成
- root_path を作成
- https://github.com/quest-academia/qa-rails-ec-training-azalea/issues/40
なし
ユーザー作成(新規登録)画面は未実装のため、"#"を仮置きしている。
- 過去の自分の実装を参考にした。
- https://github.com/quest-academia/qa-rails-ec-training-azalea/pull/77
> #40 TOPページを作成

- app/controllers/orders_controller.rb
- app/models/order.rb
- app/models/order_detail.rb
- app/views/orders/show.html.erb
- config/routes.rb
注文詳細画面の実装。
- https://github.com/quest-academia/qa-rails-ec-training-azalea/issues/30
- #18 にて実装している箇所が、rubocopによって微修正されたが、ここでコミットするのはどうだろうか、と思いaddせずに放置している。
- コミットをもっと細かく分けるべきだったかもしれない。(忘れていた)
金額の数値は、3桁ごとにコンマを打った方が見栄えが良いと考えたが、実装方法が分からず、とりあえず後回しにした。
- 過去に自分が実装したところを参考に、実装した。
- https://github.com/quest-academia/qa-rails-ec-training-azalea/pull/68
> #30 注文詳細画面

- app/views/layouts/_header.html.erb
ヘッダーの修正
- 見た目: ログイン状態による、メニューの表示分け
- 機能: リンクの有効化
- https://github.com/quest-academia/qa-rails-ec-training-azalea/issues/42
なし
商品検索、カート、注文履歴、に対するリンク機能の実装。rotes と view が未実装のため。
- #36 で実装した表示分けとlink_to を参考にした。
> #42 ヘッダー修正

- app/views/static_pages/home.html.erb
> fix-top-page TOPページのボタンリンクを有効化

- app/models/order.rb
- app/models/shipment_status.rb
- spec/rails_helper.rb
> Install rspec

- spec/models/product_spec.rb
> ProductモデルのRSpec作成

- app/controllers/users_controller.rb
- app/helpers/sessions_helper.rb
- app/views/layouts/_header.html.erb
- app/views/sessions/new.html.erb
- app/views/static_pages/home.html.erb
- config/routes.rb
- ゲストログイン機能の実装
- guest_login メソッドの作成
- ゲストログインボタンの設置
- ゲストログインユーザーの情報更新をできないようにする
- https://github.com/quest-academia/qa-rails-ec-training-azalea/issues/90
- guest_login メソッドの実装方法は妥当か。
- ゲストログインユーザーの削除防止(ユーザー退会機能未実装のため)
- おそらく、`users_controller` 内の、`before_action :guest_user, only: :update` を`before_action :guest_user, only: [:destroy, :update]`に変更すれば、退会機能にもそのまま使えるのではないか、と考えている。(だとしたら、アラート"ゲストユーザー情報の再設定はできません。"は不適切かも)
- [ゲストログイン機能の実装方法](https://qiita.com/take18k_tech/items/35f9b5883f5be4c6e104)
> #90 ゲストログイン

- app/controllers/orders_controller.rb
orders/:idページへのアクセス時に発生するエラーに対処しました。
session_helperのcorrect_userメソッドの代わりに、似たロジックをもつcorrect_users_orderを定義し、適用させました。
https://stackoverflow.com/questions/15693479/couldnt-find-user-with-id-activerecordrecordnotfound
> Error handling エラー対処

- app/controllers/users_controller.rb
- app/models/product.rb
- app/views/users/edit.html.erb
- ユーザー退会機能実装
- products と order_details をhas_many で繋ぎ込んだ
- https://github.com/quest-academia/qa-rails-ec-training-azalea/issues/43
- 実装後に、rails チュートリアルではどうなっているのだろうか、と思って、見てみたら、`user = User.find(params[:id])`と、`user.destroy!`はまとめて、`User.find(params[:id]).destroy`と書かれていたが、こちらの方が良いか。
なし
- [エラー `Mysql2::Error: Cannot delete or update a parent row:` 発生時](https://qiita.com/zenfumi/items/c1cf62b88761858884ec)
> #43 ユーザー退会

- app/controllers/orders_controller.rb
- app/views/orders/show.html.erb
注文キャンセル機能の実装
https://github.com/quest-academia/qa-rails-ec-training-azalea/issues/61
https://github.com/quest-academia/qa-rails-ec-training-azalea/commit/6081ce3214fd85383323800849cbab51eb957c10
> #61 注文キャンセル 

- app/views/products/show.html.erb
不要なコメントアウトを削除し、商品検索画面に遷移するlink_toメソッドを作成しました。
> #modify_comment_outs 

- app/controllers/products_controller.rb
- app/models/product.rb
- app/views/products/index.html.erb
- db/seeds.rb
商品検索機能の実装
⚫︎商品の商品名カラムに対して部分一致の検索をかける
⚫︎検索ワードがないときは、全商品を表示させる
⚫︎「商品カテゴリ」のセレクトボックスにはseedのDBにあるものだけが表示されるようにする
⚫︎「商品カテゴリ」のセレクトボックスを選択したときにその商品カテゴリに絞って検索がかかるようにする
https://github.com/quest-academia/qa-rails-ec-training-azalea/issues/44
> #44 商品検索画面(検索ロジック)
